name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '13'
          postgresql db: ${{ secrets.PGDATABASE }}
          postgresql user: ${{ secrets.PGUSERNAME }}
          postgresql password: ${{ secrets.PGPASSWORD }}
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run heroku-postbuild
          start: npm start
        env:
          PGHOST: localhost
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGUSERNAME: ${{ secrets.PGUSERNAME }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          CSRF_TOKEN_SECRET: ${{ secrets.CSRF_TOKEN_SECRET }}
